eeazycrm/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

import os

from .config import DevelopmentConfig, TestConfig, ProductionConfig

# database handle
db = SQLAlchemy(session_options={"autoflush": False})

# encryptor handle
bcrypt = Bcrypt()

# manage user login
login_manager = LoginManager()

# function name of the login route that
# tells the path which facilitates authentication
login_manager.login_view = 'users.login'


def run_install(app_ctx):
    from eeazycrm.install.routes import install
    app_ctx.register_blueprint(install)
    return app_ctx


def create_app(config_class=ProductionConfig):
    app = Flask(__name__, instance_relative_config=True)

    if os.getenv('FLASK_ENV') == 'development':
        config_class = DevelopmentConfig()
    elif os.getenv('FLASK_ENV') == 'production':
        config_class = ProductionConfig()
    elif os.getenv('FLASK_ENV') == 'testing':
        config_class = TestConfig()

    app.config.from_object(config_class)
    app.url_map.strict_slashes = False
    app.jinja_env.globals.update(zip=zip)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    with app.app_context():
        # check if the config table exists, otherwise run install
        engine = db.get_engine(app)
        if not engine.dialect.has_table(engine, 'app_config'):
            return run_install(app)
        else:
            from eeazycrm.settings.models import AppConfig
            row = AppConfig.query.first()
            if not row:
                return run_install(app)

        # application is installed so extends the config
        from eeazycrm.settings.models import AppConfig, Currency, TimeZone
        app_cfg = AppConfig.query.first()
        app.config['def_currency'] = Currency.get_currency_by_id(app_cfg.default_currency)
        app.config['def_tz'] = TimeZone.get_tz_by_id(app_cfg.default_timezone)

        # include the routes
        # from eeazycrm import routes
        from eeazycrm.main.routes import main
        from eeazycrm.users.routes import users
        from eeazycrm.leads.routes import leads
        from eeazycrm.accounts.routes import accounts
        from eeazycrm.contacts.routes import contacts
        from eeazycrm.deals.routes import deals
        from eeazycrm.settings.routes import settings
        from eeazycrm.settings.app_routes import app_config
        from eeazycrm.reports.routes import reports

        # register routes with blueprint
        app.register_blueprint(main)
        app.register_blueprint(users)
        app.register_blueprint(settings)
        app.register_blueprint(app_config)
        app.register_blueprint(leads)
        app.register_blueprint(accounts)
        app.register_blueprint(contacts)
        app.register_blueprint(deals)
        app.register_blueprint(reports)
        return app

eeazycrm/contacts/routes.py
from flask_login import current_user, login_required
from flask import render_template, flash, url_for, redirect, request, Blueprint, session
import json
from wtforms import Label
from sqlalchemy import or_, text
from datetime import date, timedelta

from eeazycrm import db
from .models import Contact
from eeazycrm.common.paginate import Paginate
from eeazycrm.common.filters import CommonFilters
from .forms import NewContact, FilterContacts, filter_contacts_adv_filters_query
from eeazycrm.users.utils import upload_avatar

from eeazycrm.rbac import check_access

contacts = Blueprint('contacts', __name__)


def set_filters(f_id, module):
    today = date.today()
    filter_d = True
    if f_id == 1:
        filter_d = text("Date(%s.date_created)='%s'" % (module, today))
    elif f_id == 2:
        filter_d = text("Date(%s.date_created)='%s'" % (module, (today - timedelta(1))))
    elif f_id == 3:
        filter_d = text("Date(%s.date_created) > current_date - interval '7' day" % module)
    elif f_id == 4:
        filter_d = text("Date(%s.date_created) > current_date - interval '30' day" % module)
    return filter_d


def set_date_filters(filters, module, key):
    filter_d = True
    if request.method == 'POST':
        if filters.advanced_user.data:
            filter_d = set_filters(filters.advanced_user.data['id'], module)
            session[key] = filters.advanced_user.data['id']
        else:
            session.pop(key, None)
    else:
        if key in session:
            filter_d = set_filters(session[key], module)
            filters.advanced_user.data = filter_contacts_adv_filters_query()[session[key] - 1]
    return filter_d


def reset_contacts_filters():
    if 'contacts_owner' in session:
        session.pop('contacts_owner', None)
    if 'contacts_search' in session:
        session.pop('contacts_search', None)
    if 'contacts_acc_owner' in session:
        session.pop('contacts_acc_owner', None)
    if 'contacts_date_created' in session:
        session.pop('contacts_date_created', None)


@contacts.route("/contacts", methods=['GET', 'POST'])
@login_required
@check_access('contacts', 'view')
def get_contacts_view():
    filters = FilterContacts()
    search = CommonFilters.set_search(filters, 'contacts_search')
    owner = CommonFilters.set_owner(filters, 'Contact', 'contacts_owner')
    account = CommonFilters.set_accounts(filters, 'Contact', 'contacts_acc_owner')
    advanced_filters = set_date_filters(filters, 'Contact', 'contacts_date_created')

    query = Contact.query.filter(or_(
            Contact.first_name.ilike(f'%{search}%'),
            Contact.last_name.ilike(f'%{search}%'),
            Contact.email.ilike(f'%{search}%'),
            Contact.phone.ilike(f'%{search}%'),
            Contact.mobile.ilike(f'%{search}%'),
            Contact.address_line.ilike(f'%{search}%'),
            Contact.addr_state.ilike(f'%{search}%'),
            Contact.addr_city.ilike(f'%{search}%'),
            Contact.post_code.ilike(f'%{search}%')
        ) if search else True)\
        .filter(account) \
        .filter(owner) \
        .filter(advanced_filters) \
        .order_by(Contact.date_created.desc())

    return render_template("contacts/contacts_list.html", title="Contacts View",
                           contacts=Paginate(query=query), filters=filters)


@contacts.route("/contacts/acc/<int:account_id>")
@login_required
@check_access('contacts', 'view')
def get_account_contacts(account_id):
    items = Contact.query\
        .filter_by(account_id=account_id)\
        .order_by(Contact.date_created.desc())\
        .all()

    d = []
    for item in items:
        f = {'id': item.id, 'name': item.get_contact_name()}
        d.append(f)
    return json.dumps(d)


@contacts.route("/contacts/new", methods=['GET', 'POST'])
@login_required
@check_access('contacts', 'create')
def new_contact():
    form = NewContact()
    if request.method == 'POST':
        if form.validate_on_submit():
            contact = Contact(first_name=form.first_name.data,
                              last_name=form.last_name.data,
                              email=form.email.data,
                              phone=form.phone.data,
                              mobile=form.mobile.data,
                              address_line=form.address_line.data,
                              addr_state=form.addr_state.data,
                              addr_city=form.addr_city.data,
                              post_code=form.post_code.data,
                              country=form.country.data,
                              notes=form.notes.data)

            contact.account = form.accounts.data

            if form.avatar.data:
                picture_file = upload_avatar(contact, form.avatar.data)
                contact.avatar = picture_file

            if current_user.is_admin:
                contact.contact_owner = form.assignees.data
            else:
                contact.contact_owner = current_user

            db.session.add(contact)
            db.session.commit()
            flash('Contact has been successfully created!', 'success')
            return redirect(url_for('contacts.get_contacts_view'))
        else:
            print(form.errors)

            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("contacts/new_contact.html", title="New Contact", form=form)


@contacts.route("/contacts/edit/<int:contact_id>", methods=['GET', 'POST'])
@login_required
@check_access('contacts', 'update')
def update_contact(contact_id):
    contact = Contact.get_contact(contact_id)
    if not contact:
        return redirect(url_for('contacts.get_contacts_view'))

    form = NewContact()
    if request.method == 'POST':
        if form.validate_on_submit():
            contact.first_name = form.first_name.data
            contact.last_name = form.last_name.data
            contact.email = form.email.data
            contact.phone = form.phone.data
            contact.mobile = form.mobile.data
            contact.address_line = form.address_line.data
            contact.addr_state = form.addr_state.data
            contact.addr_city = form.addr_city.data
            contact.post_code = form.post_code.data
            contact.country = form.country.data
            contact.contact_owner = form.assignees.data
            contact.account = form.accounts.data
            contact.notes = form.notes.data
            db.session.commit()
            flash('The contact has been successfully updated', 'success')
            return redirect(url_for('contacts.get_contact_view', contact_id=contact.id))
        else:
            print(form.errors)
            flash('Contact update failed! Form has errors', 'danger')
    elif request.method == 'GET':
        form.first_name.data = contact.first_name
        form.last_name.data = contact.last_name
        form.email.data = contact.email
        form.phone.data = contact.phone
        form.mobile.data = contact.mobile
        form.address_line.data = contact.address_line
        form.addr_state.data = contact.addr_state
        form.addr_city.data = contact.addr_city
        form.post_code.data = contact.post_code
        form.country.data = contact.country
        form.assignees.data = contact.contact_owner
        form.accounts.data = contact.account
        form.notes.data = contact.notes
        form.submit.label = Label('update_contact', 'Update Contact')
    return render_template("contacts/new_contact.html", title="Update Contact", form=form)


@contacts.route("/contacts/<int:contact_id>")
@login_required
@check_access('contacts', 'view')
def get_contact_view(contact_id):
    contact = Contact.query.filter_by(id=contact_id).first()
    return render_template("contacts/contact_view.html", title="View Contact", contact=contact)


@contacts.route("/contacts/del/<int:contact_id>")
@login_required
@check_access('contacts', 'delete')
def delete_contact(contact_id):
    Contact.query.filter_by(id=contact_id).delete()
    db.session.commit()
    flash('Contact removed successfully!', 'success')
    return redirect(url_for('contacts.get_contacts_view'))


@contacts.route("/contacts/reset_filters")
@login_required
@check_access('contacts', 'view')
def reset_filters():
    reset_contacts_filters()
    return redirect(url_for('contacts.get_contacts_view'))

eeazycrm/install/routes.py
from flask import render_template, session, url_for, redirect, Blueprint, request
from eeazycrm import db, bcrypt
import os
import sys
from flask import current_app
from tzlocal import get_localzone

from eeazycrm.settings.models import Currency, TimeZone, AppConfig
from eeazycrm.leads.models import LeadSource, LeadStatus, Lead
from eeazycrm.accounts.models import Account
from eeazycrm.contacts.models import Contact
from eeazycrm.deals.models import DealStage, Deal
from eeazycrm.users.models import Role, Resource, User

from eeazycrm.install.forms import NewSystemUser, CurrencyTz, FinishInstall
from eeazycrm.install.data.currency_timezone import INSERT_SQL
from eeazycrm.install.data.sample_data import SAMPLE_DATA

install = Blueprint('install', __name__)


@install.route("/", methods=['GET', 'POST'])
@install.route("/install", methods=['GET', 'POST'])
def sys_info():

    # create empty tables
    db.create_all()

    v = tuple(sys.version.split('.'))
    if v and int(v[0]) < 3 and int(v[1]) < 5:
        return render_template("install/error.html", title="Eeazy CRM installation failed",
                               reason=f"Python version >= {current_app.config['PYTHON_VER_MIN_REQUIRED']} is required for EeazyCRM")
    env_vars = {
        'email_user': True if os.getenv('EMAIL_USER') else False,
        'email_pass': True if os.getenv('EMAIL_PASS') else False
    }
    return render_template("install/sys_info.html", title="System Information",
                           system_info=os.uname(), py_ver=sys.version, env_vars=env_vars)


@install.route("/install/sys_user", methods=['GET', 'POST'])
def setup_sys_user():
    form = NewSystemUser()
    if request.method == 'POST':
        if form.validate_on_submit():
            hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            session['admin_first_name'] = form.first_name.data
            session['admin_last_name'] = form.last_name.data
            session['admin_email'] = form.email.data
            session['admin_password'] = hashed_pwd

            # create currency & timezone data
            db.session.execute(INSERT_SQL)
            db.session.commit()

            return redirect(url_for('install.ex_settings'))
    return render_template("install/sys_user.html", title="Create System User (admin)",
                           form=form)


@install.route("/install/extra_settings", methods=['GET', 'POST'])
def ex_settings():
    # insert currency & timezone tables with data
    form = CurrencyTz()
    if request.method == 'POST':
        if form.validate_on_submit():
            session['app_currency_name'] = form.currency.data.name + f'({form.currency.data.symbol})' if form.currency.data.symbol else ''
            session['app_currency_id'] = form.currency.data.id
            session['app_tz_name'] = form.time_zone.data.name
            session['app_tz_id'] = form.time_zone.data.id
            return redirect(url_for('install.finish'))
    elif request.method == 'GET':
        form.currency.data = Currency.get_currency_by_id(142)
        local_tz = get_localzone()
        if local_tz:
            form.time_zone.data = TimeZone.get_tz_by_name(str(local_tz))
        else:
            form.time_zone.data = TimeZone.get_tz_by_id(380)
    return render_template("install/extra_settings.html", title="Set Currency & TimeZone", form=form)


def empty_setup():
    # create system roles & resources
    role = Role(name='general')
    role.resources.append(
        Resource(
            name='staff',
            can_view=True,
            can_edit=False,
            can_create=False,
            can_delete=False
        )
    )

    role.resources.append(
        Resource(
            name='leads',
            can_view=True,
            can_edit=False,
            can_create=True,
            can_delete=False
        )
    )

    role.resources.append(
        Resource(
            name='accounts',
            can_view=True,
            can_edit=False,
            can_create=True,
            can_delete=False
        )
    )

    role.resources.append(
        Resource(
            name='contacts',
            can_view=True,
            can_edit=True,
            can_create=True,
            can_delete=False
        )
    )

    role.resources.append(
        Resource(
            name='deals',
            can_view=True,
            can_edit=False,
            can_create=True,
            can_delete=False
        )
    )

    # create user
    user = User(first_name=session['admin_first_name'],
                last_name=session['admin_last_name'],
                email=session['admin_email'],
                password=session['admin_password'],
                is_admin=True,
                is_first_login=True,
                is_user_active=True
                )

    db.session.add(role)
    db.session.add(user)

    # add system deal stages
    db.session.add(DealStage(stage_name="Deal Won", display_order=1, close_type='won'))
    db.session.add(DealStage(stage_name="Deal Lost", display_order=2, close_type='lost'))


@install.route("/install/finish", methods=['GET', 'POST'])
def finish():
    form = FinishInstall()
    data = {
        'def_currency': session['app_currency_name'],
        'def_tz': session['app_tz_name']
    }
    if request.method == 'POST':
        if form.validate_on_submit():

            if form.import_sample_data.data:
                db.session.execute(SAMPLE_DATA % (
                    session['admin_first_name'],
                    session['admin_last_name'],
                    session['admin_email'],
                    session['admin_password']))
            else:
                empty_setup()

            # create configuration
            app_cfg = AppConfig(
                default_currency=session['app_currency_id'],
                default_timezone=session['app_tz_id']
            )

            print(session['app_currency_id'])

            # create application config
            db.session.add(app_cfg)
            db.session.commit()

            return render_template("install/complete.html", title="Hurray! Installation Complete!")
    return render_template("install/finish.html", title="We're all set! Let's finish Installation",
                           data=data, form=form)


@current_app.errorhandler(404)
def page_not_found(error):
    return redirect(url_for('install.sys_info'))

eeazycrm/templates/contacts/contact_view.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ url_for('contacts.update_contact', contact_id=contact.id) }}"
               class="btn btn-md btn-outline-primary mr-2" role="button">
                <span data-feather="edit-2"></span>
                  Edit
            </a>
            <a href="{{ url_for('contacts.get_contacts_view') }}" class="btn btn-md btn-outline-secondary" role="button">
                <span data-feather="arrow-left"></span>
                  Back to List
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-5">
            <ul class="list-group list-group-flush">
                <li class="list-group-item g_field col-12">
                    <div class="row">
                      <div class="col-6">
                          <div class="label">First Name</div>
                          <div class="text">{{ contact.first_name if contact.last_name else '_' }}</div>
                      </div>
                      <div class="col-6">
                          <div class="label">Last Name</div>
                          <div class="text">{{ contact.last_name if contact.last_name else '_' }}</div>
                      </div>
                  </div>
                </li>
                <li class="list-group-item g_field">
                  <div class="label">Email</div>
                    {% if contact.email %}
                        <div class="text">
                            <span data-feather="mail" class="mr-1"></span>
                            <a href="mailto: {{ contact.email }}">{{ contact.email }}</a>
                        </div>
                    {% else %}
                        <div class="text"><span data-feather="mail"></span> _</div>
                    {% endif %}
              </li>
                <li class="list-group-item g_field col-12">
                    <div class="row">
                      <div class="col-6">
                          <div class="label">Phone</div>
                          <div class="text">
                              <span data-feather="phone" class="mr-1"></span> {{ contact.phone if contact.phone else '_' }}
                          </div>
                      </div>
                      <div class="col-6">
                          <div class="label">Mobile</div>
                          <div class="text">
                              <span data-feather="smartphone" class="mr-1"></span> {{ contact.mobile if contact.mobile else '_' }}
                          </div>
                      </div>
                    </div>
              </li>

                <li class="list-group-item g_field">
                  <div class="label">Owner</div>
                    {% if contact.contact_owner %}
                    <div class="text">
                        <div class="mt-1">
                            {% with owner=contact.contact_owner %}{% include 'common/owner_cell.html' %}{% endwith %}
                        </div>
                    </div>
                    {% else %}
                        <div class="text">_</div>
                    {% endif %}
              </li>

            </ul>
        </div>
        <div class="col-5">
            <ul class="list-group list-group-flush">
                <li class="list-group-item g_field col-12">
                  <div class="label">Address</div>
                  <div class="text">{{ contact.address_line if contact.address_line else '_' }}</div>
              </li>
              <li class="list-group-item g_field col-12">
                  <div class="row">
                      <div class="col-6">
                          <div class="label">State</div>
                          <div class="text">{{ contact.addr_state if contact.addr_state else '_' }}</div>
                      </div>
                      <div class="col-6">
                          <div class="label">City</div>
                          <div class="text">{{ contact.addr_city if contact.addr_city else '_' }}</div>
                      </div>
                  </div>
              </li>
                <li class="list-group-item g_field col-12">
                    <div class="row">
                        <div class="col-6">
                            <div class="label">Postcode</div>
                            <div class="text">{{ contact.post_code if contact.post_code else '_' }}</div>
                        </div>
                        <div class="col-6">
                            <div class="label">Country</div>
                            <div class="text">{{ contact.country if contact.country else '_' }}</div>
                        </div>
                    </div>
              </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-10">
            <div></div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item g_field col-12">
                    <div class="label">Notes</div>
                    <div class="text">{{ contact.notes if contact.notes else '_' }}</div>
                </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-10 mt-4">
            <ul class="nav nav-tabs">
              <li class="nav-item">
                  <a href="#deals-tab" data-toggle="tab" role="tab" aria-controls="deals" aria-selected="true"
                     class="nav-link active">Deals</a>
              </li>
            </ul>
            <div class="tab-content p-4">
              <div class="tab-pane fade show active" id="deals-tab" role="tabpanel" aria-labelledby="deals-tab">
                <div class="mt-2 mb-4">Deals associated with this contact</div>
                  {% if contact.deals|length > 0 %}
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Account</th>
                                    <th>Price (USD)</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for deal in contact.deals %}
                                    <tr>
                                        <td>{{ deal.title }}</td>
                                        <td>{{ deal.account.name }}</td>
                                        <td>{{ deal.expected_close_price }}</td>
                                        <td>{{ deal.title }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                  {% else %}
                    <p>No deals</p>
                  {% endif %}
              </div>
            </div>
        </div>
    </div>
    {% endblock %}

eeazycrm/templates/contacts/contacts_list.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            {% if current_user.is_admin %}
            <a class="btn btn-sm btn-outline-secondary mr-2" role="button" href="{{ url_for('leads.import_bulk_leads') }}">
                <span data-feather="upload"></span>
                  import contacts ...
            </a>
            {% endif %}
            <a class="btn btn btn-sm btn-outline-primary" role="button" href="{{ url_for('contacts.new_contact') }}">
                <span data-feather="plus"></span>
                  New
            </a>
        </div>
    </div>
    {% include "contacts/filters.html" %}
    {% if contacts.items()|length > 0 %}
        <div class="table-responsive">
            <table class="table table-striped table-hover fixed-layout-table">
              <thead class="thead-light">
                <tr>
                  <th width="40" scope="col">
                      <input type="checkbox" id="select_all" value="all" />
                  </th>
                    <th width="150"></th>
                  <th width="150" scope="col">First Name</th>
                  <th width="150" scope="col">Last Name</th>
                    <th width="300" scope="col">Account</th>
                  <th width="300" scope="col">Email</th>
                    <th width="150" scope="col">Phone</th>
                    <th width="200" scope="col">Mobile</th>
                    <th width="250" scope="col">Address</th>
                    <th width="250" scope="col">State</th>
                    <th width="200" scope="col">City</th>
                    <th width="100" scope="col">Pincode</th>
                    <th width="100" scope="col">Country</th>
                    <th width="200" scope="col">Owner</th>
                    <th width="200" scope="col">Date Created</th>
                </tr>
              </thead>
              <tbody>
                {% for contact in contacts.items() %}
                <tr>
                  <th scope="row">
                      <input class="cb" type="checkbox" value="{{ contact.id }}" />
                  </th>
                    <th>
                        <a href="{{ url_for('contacts.update_contact', contact_id=contact.id) }}"
                           class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="edit"></span>
                        </a>
                        <a href="#" class="btn btn-outline-secondary btn-sm mr-1"
                           data-target="#singleContactDeleteModal_{{ contact.id }}" data-toggle="modal" role="button">
                            <span data-feather="trash"></span>
                        </a>
                        {% with contact_id=contact.id %}
                            {% include 'contacts/single_contact_delete_modal.html' %}
                        {% endwith %}
                        <a href="{{ url_for('contacts.get_contact_view', contact_id=contact.id) }}"
                           class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="arrow-up-right"></span>
                        </a>
                    </th>
                  <td>{{ contact.first_name }}</td>
                  <td>{{ contact.last_name }}</td>
                    <td>{{ contact.account.name }}</td>
                    <td>{{ contact.email }}</td>
                    <td>{{ contact.phone }}</td>
                    <td>{{ contact.mobile }}</td>
                     <td>{{ contact.address_line }}</td>
                     <td>{{ contact.addr_state }}</td>
                     <td>{{ contact.addr_city }}</td>
                     <td>{{ contact.pin_code }}</td>
                     <td>{{ contact.country }}</td>
                    <td>{% with owner=contact.contact_owner %}{% include 'common/owner_cell.html' %}{% endwith %}</td>
                    <td>{{ contact.date_created.strftime('%Y-%m-%d') if contact.date_created }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>

        <!-- pagination -->
        {% if contacts.total_records > 10 %}
            {% with view_id="contacts.get_contacts_view", items=contacts %}
                {% include "common/pagination.html" %}
            {% endwith %}
        {% endif %}
    {% else %}
        <div class="container text-center pt-4">
            <div><span data-feather="eye-off"></span></div>
            <p>No contacts found. Please create your first contact.</p>
        </div>
    {%  endif %}
<script>
    $(document).ready(function() {
        $('#select_all').on('click', function() {
            if ($(this).is(':checked')) {
                $('.cb').prop('checked', true);
            } else {
                $('.cb').prop('checked', false);
            }
        });
    });
</script>
{% endblock %}

eeazycrm/templates/contacts/filters.html
<form class="form-lead-filter" method="POST">
    {{ filters.hidden_tag() }} <!-- security 'csrf' token -->
    <div class="d-flex flex-column justify-content-between flex-wrap flex-md-nowrap pb-4 mb-3">
        <div class="mb-2"><strong>Filters</strong></div>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="col-md-3 pl-0">
                {{ filters.txt_search(class="form-control from-control-lg", placeholder="search contacts ...") }}
            </div>
            <div class="col-md-3 pl-0">
                <div class="form-group text-left">
                    {{ filters.accounts(class="my-select form-control") }}
                </div>
            </div>
            {% if current_user.is_admin %}
            <div class="col-md-3 pl-0">
                <div class="form-group text-left">
                    {{ filters.assignees(class="my-select form-control") }}
                </div>
            </div>
            {% endif %}
            <div class="col-md-3 pl-0">
                <div class="form-group text-left">
                     {{ filters.advanced_user(class="my-select form-control") }}
                </div>
            </div>
        </div>
        <div class="btn-toolbar mb-1 mb-md-0">
            <div class="col-md-3 pl-0">
                {{ filters.submit(class="btn btn-md btn-outline-info mr-2") }}
                <a href="{{ url_for('contacts.reset_filters') }}" class="btn btn-md btn-outline-secondary" role="button">
                    <span data-feather="x-circle"></span>
                </a>
            </div>
        </div>
    </div>
</form>