eeazycrm/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.widgets import TextArea
from wtforms.validators import DataRequired, Email
from wtforms_sqlalchemy.fields import QuerySelectField

from eeazycrm.users.models import User


class NewAccount(FlaskForm):
    name = StringField('Account Name', validators=[DataRequired(message='Account name is mandatory')])
    website = StringField('Website')
    email = StringField('Email',
                        validators=[DataRequired(message='Email address is mandatory'),
                                    Email(message='Please enter a valid email address e.g. abc@yourcompany.com')])
    phone = StringField('Phone')
    address_line = StringField('Address')
    addr_state = StringField('State')
    addr_city = StringField('City')
    post_code = StringField('Postcode')
    country = StringField('Country')
    notes = StringField('Notes', widget=TextArea())
    assignees = QuerySelectField('Assign To', query_factory=User.user_list_query, get_pk=lambda a: a.id,
                                 get_label=User.get_label, default=User.get_current_user)
    submit = SubmitField('Create New Account')


def filter_accounts_adv_filters_query():
    return [
        {'id': 1, 'title': 'Active'},
        {'id': 2, 'title': 'Inactive'},
        {'id': 3, 'title': 'Created Today'},
        {'id': 4, 'title': 'Created Yesterday'},
        {'id': 5, 'title': 'Created In Last 7 Days'},
        {'id': 6, 'title': 'Created In Last 30 Days'}
    ]


class FilterAccounts(FlaskForm):
    txt_search = StringField()
    assignees = QuerySelectField(query_factory=User.user_list_query, get_pk=lambda a: a.id,
                                 get_label=User.get_label, allow_blank=True, blank_text='[-- Select Owner --]')
    advanced_user = QuerySelectField(query_factory=filter_accounts_adv_filters_query,
                                     get_pk=lambda a: a['id'],
                                     get_label=lambda a: a['title'],
                                     allow_blank=True, blank_text='[-- advanced filter --]')

    submit = SubmitField('Filter Accounts')

eeazycrm/contacts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField
from wtforms.widgets import TextArea
from wtforms.validators import DataRequired, Email
from wtforms_sqlalchemy.fields import QuerySelectField

from eeazycrm.users.models import User
from eeazycrm.accounts.models import Account


class NewContact(FlaskForm):
    first_name = StringField('First Name')
    last_name = StringField('First Name', validators=[DataRequired(message='Last name is mandatory')])
    email = StringField('Email',
                        validators=[DataRequired(message='Email address is mandatory'),
                                    Email(message='Please enter a valid email address e.g. abc@yourcompany.com')])
    phone = StringField('Phone')
    mobile = StringField('Mobile')
    avatar = FileField('Contact Avatar', validators=[FileAllowed(['jpg', 'jpeg', 'png'])])
    address_line = StringField('Address')
    addr_state = StringField('State')
    addr_city = StringField('City')
    post_code = StringField('Postcode')
    country = StringField('Country')
    notes = StringField('Notes', widget=TextArea())
    accounts = QuerySelectField('Account', query_factory=Account.account_list_query, get_pk=lambda a: a.id,
                                 get_label=Account.get_label, blank_text='Select An Account', allow_blank=True,
                                validators=[DataRequired(message='Please choose an account for the contact')])
    assignees = QuerySelectField('Assign To', query_factory=User.user_list_query, get_pk=lambda a: a.id,
                                 get_label=User.get_label, default=User.get_current_user)
    submit = SubmitField('Create New Contact')


def filter_contacts_adv_filters_query():
    return [
        {'id': 1, 'title': 'Created Today'},
        {'id': 2, 'title': 'Created Yesterday'},
        {'id': 3, 'title': 'Created In Last 7 Days'},
        {'id': 4, 'title': 'Created In Last 30 Days'}
    ]


class FilterContacts(FlaskForm):
    txt_search = StringField()
    accounts = QuerySelectField(query_factory=Account.account_list_query, get_pk=lambda a: a.id,
                                get_label=Account.get_label, blank_text='[-- Select Account--]', allow_blank=True)
    assignees = QuerySelectField(query_factory=User.user_list_query, get_pk=lambda a: a.id,
                                 get_label=User.get_label, allow_blank=True, blank_text='[-- Select Owner --]')
    advanced_user = QuerySelectField(query_factory=filter_contacts_adv_filters_query,
                                     get_pk=lambda a: a['id'],
                                     get_label=lambda a: a['title'],
                                     allow_blank=True, blank_text='[-- advanced filter --]')

    submit = SubmitField('Filter Contacts')

eeazycrm/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

import os

from .config import DevelopmentConfig, TestConfig, ProductionConfig

# database handle
db = SQLAlchemy(session_options={"autoflush": False})

# encryptor handle
bcrypt = Bcrypt()

# manage user login
login_manager = LoginManager()

# function name of the login route that
# tells the path which facilitates authentication
login_manager.login_view = 'users.login'


def run_install(app_ctx):
    from eeazycrm.install.routes import install
    app_ctx.register_blueprint(install)
    return app_ctx


def create_app(config_class=ProductionConfig):
    app = Flask(__name__, instance_relative_config=True)

    if os.getenv('FLASK_ENV') == 'development':
        config_class = DevelopmentConfig()
    elif os.getenv('FLASK_ENV') == 'production':
        config_class = ProductionConfig()
    elif os.getenv('FLASK_ENV') == 'testing':
        config_class = TestConfig()

    app.config.from_object(config_class)
    app.url_map.strict_slashes = False
    app.jinja_env.globals.update(zip=zip)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    with app.app_context():
        # check if the config table exists, otherwise run install
        engine = db.get_engine(app)
        if not engine.dialect.has_table(engine, 'app_config'):
            return run_install(app)
        else:
            from eeazycrm.settings.models import AppConfig
            row = AppConfig.query.first()
            if not row:
                return run_install(app)

        # application is installed so extends the config
        from eeazycrm.settings.models import AppConfig, Currency, TimeZone
        app_cfg = AppConfig.query.first()
        app.config['def_currency'] = Currency.get_currency_by_id(app_cfg.default_currency)
        app.config['def_tz'] = TimeZone.get_tz_by_id(app_cfg.default_timezone)

        # include the routes
        # from eeazycrm import routes
        from eeazycrm.main.routes import main
        from eeazycrm.users.routes import users
        from eeazycrm.leads.routes import leads
        from eeazycrm.accounts.routes import accounts
        from eeazycrm.contacts.routes import contacts
        from eeazycrm.deals.routes import deals
        from eeazycrm.settings.routes import settings
        from eeazycrm.settings.app_routes import app_config
        from eeazycrm.reports.routes import reports

        # register routes with blueprint
        app.register_blueprint(main)
        app.register_blueprint(users)
        app.register_blueprint(settings)
        app.register_blueprint(app_config)
        app.register_blueprint(leads)
        app.register_blueprint(accounts)
        app.register_blueprint(contacts)
        app.register_blueprint(deals)
        app.register_blueprint(reports)
        return app

eeazycrm/leads/routes.py
import pandas as pd
from sqlalchemy import or_
from wtforms import Label

from flask import Blueprint, session, Response
from flask_login import current_user, login_required
from flask import render_template, flash, url_for, redirect, request

from eeazycrm import db
from .models import Lead
from eeazycrm.common.paginate import Paginate
from eeazycrm.common.filters import CommonFilters
from .filters import set_date_filters, set_source, set_status
from .forms import NewLead, ImportLeads, ConvertLead, \
    FilterLeads, BulkOwnerAssign, BulkLeadSourceAssign, BulkLeadStatusAssign, BulkDelete

from eeazycrm.rbac import check_access, is_admin

leads = Blueprint('leads', __name__)


def reset_lead_filters():
    if 'lead_owner' in session:
        session.pop('lead_owner', None)
    if 'lead_search' in session:
        session.pop('lead_search', None)
    if 'lead_date_created' in session:
        session.pop('lead_date_created', None)
    if 'lead_source' in session:
        session.pop('lead_source', None)
    if 'lead_status' in session:
        session.pop('lead_status', None)


@leads.route("/leads", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'view')
def get_leads_view():
    filters = FilterLeads()
    search = CommonFilters.set_search(filters, 'lead_search')
    owner = CommonFilters.set_owner(filters, 'Lead', 'lead_owner')
    advanced_filters = set_date_filters(filters, 'lead_date_created')
    source_filter = set_source(filters, 'lead_source')
    status_filter = set_status(filters, 'lead_status')

    query = Lead.query \
        .filter(or_(
            Lead.title.ilike(f'%{search}'),
            Lead.first_name.ilike(f'%{search}'),
            Lead.last_name.ilike(f'%{search}'),
            Lead.email.ilike(f'%{search}'),
            Lead.company_name.ilike(f'%{search}'),
            Lead.phone.ilike(f'%{search}'),
            Lead.mobile.ilike(f'%{search}'),
        ) if search else True) \
        .filter(source_filter) \
        .filter(status_filter) \
        .filter(owner) \
        .filter(advanced_filters) \
        .order_by(Lead.date_created.desc())

    bulk_form = {
        'owner': BulkOwnerAssign(),
        'lead_source': BulkLeadSourceAssign(),
        'lead_status': BulkLeadStatusAssign(),
        'delete': BulkDelete()
    }

    return render_template("leads/leads_list.html", title="Leads View",
                           leads=Paginate(query), filters=filters, bulk_form=bulk_form)


@leads.route("/leads/new", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'create')
def new_lead():
    form = NewLead()
    if request.method == 'POST':
        if form.validate_on_submit():
            lead = Lead(title=form.title.data,
                        first_name=form.first_name.data, last_name=form.last_name.data,
                        email=form.email.data, company_name=form.company.data,
                        address_line=form.address_line.data, addr_state=form.addr_state.data,
                        addr_city=form.addr_city.data, post_code=form.post_code.data,
                        country=form.country.data, source=form.lead_source.data,
                        status=form.lead_status.data, notes=form.notes.data)

            if current_user.is_admin:
                lead.owner = form.assignees.data
            else:
                lead.owner = current_user

            db.session.add(lead)
            db.session.commit()
            flash('New lead has been successfully created!', 'success')
            return redirect(url_for('leads.get_leads_view'))
        else:
            for error in form.errors:
                print(error)
            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("leads/new_lead.html", title="New Lead", form=form)


@leads.route("/leads/edit/<int:lead_id>", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'update')
def update_lead(lead_id):
    lead = Lead.get_by_id(lead_id)
    if not lead:
        return redirect(url_for('leads.get_leads_view'))

    form = NewLead()
    if request.method == 'POST':
        if form.validate_on_submit():
            lead.title = form.title.data
            lead.first_name = form.first_name.data
            lead.last_name = form.last_name.data
            lead.email = form.email.data
            lead.company_name = form.company.data
            lead.phone = form.phone.data
            lead.mobile = form.mobile.data
            lead.address_line = form.address_line.data
            lead.addr_state = form.addr_state.data
            lead.addr_city = form.addr_city.data
            lead.post_code = form.post_code.data
            lead.country = form.country.data
            lead.owner = form.assignees.data
            lead.source = form.lead_source.data
            lead.status = form.lead_status.data
            lead.notes = form.notes.data
            db.session.commit()
            flash('The lead has been successfully updated', 'success')
            return redirect(url_for('leads.get_lead_view', lead_id=lead.id))
        else:
            print(form.errors)
            flash('User update failed! Form has errors', 'danger')
    elif request.method == 'GET':
        form.title.data = lead.title
        form.first_name.data = lead.first_name
        form.last_name.data = lead.last_name
        form.email.data = lead.email
        form.company.data = lead.company_name
        form.phone.data = lead.phone
        form.mobile.data = lead.mobile
        form.address_line.data = lead.address_line
        form.addr_state.data = lead.addr_state
        form.addr_city.data = lead.addr_city
        form.post_code.data = lead.post_code
        form.country.data = lead.country
        form.assignees.data = lead.owner
        form.lead_source.data = lead.source
        form.lead_status.data = lead.status
        form.notes.data = lead.notes
        form.submit.label = Label('update_lead', 'Update Lead')
    return render_template("leads/new_lead.html", title="Update Lead", form=form)


@leads.route("/leads/<int:lead_id>")
@login_required
@check_access('leads', 'view')
def get_lead_view(lead_id):
    lead = Lead.query.filter_by(id=lead_id).first()
    return render_template("leads/lead_view.html", title="View Lead", lead=lead)


@leads.route("/leads/del/<int:lead_id>")
@login_required
@check_access('leads', 'remove')
def delete_lead(lead_id):
    lead = Lead.query.filter_by(id=lead_id).first()
    if not lead:
        flash('The lead does not exist', 'danger')
    else:
        Lead.query.filter_by(id=lead_id).delete()
        db.session.commit()
        flash('The lead has been removed successfully', 'success')
    return redirect(url_for('leads.get_leads_view'))


@leads.route("/leads/convert/<int:lead_id>", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'view')
@check_access('accounts', 'create')
@check_access('contacts', 'create')
@check_access('deals', 'create')
def convert_lead(lead_id):
    lead = Lead.query.filter_by(id=lead_id).first()
    form = ConvertLead()
    form.account_name.data = lead.company_name
    form.account_email.data = lead.email

    if request.method == 'POST':
        if form.validate_on_submit():
            if form.use_account_information.data and form.use_contact_information.data:
                # create both account and contact

                pass
            elif form.use_account_information.data and not form.use_contact_information.data:
                # create account only (and contact if chosen from dropdown)
                if not form.account_name.data:
                    form.account_name.errors = ['Please enter account name']
                if not form.account_name.data:
                    form.account_email.errors = ['Please enter account email']
            elif not form.use_account_information.data and form.use_contact_information.data:
                pass
                # create contact only (account dropdown must be selected)
            elif not form.use_account_information.data and not form.use_contact_information.data:
                # account must be selected in dropdown (and create contact if selected in dropdown)
                if not form.accounts.data:
                    form.accounts.errors = ['Please select an account']
                pass

            flash('Leads has been successfully converted!', 'success')
        else:
            flash('Your form has errors! Please check the fields', 'danger')
    else:
        form.title.data = lead.title
    return render_template("leads/lead_convert.html", title="Convert Lead", lead=lead, form=form)


@leads.route("/leads/import", methods=['GET', 'POST'])
@login_required
@is_admin
def import_bulk_leads():
    form = ImportLeads()
    if request.method == 'POST':
        ind = 0
        if form.validate_on_submit():
            data = pd.read_csv(form.csv_file.data)

            for _, row in data.iterrows():
                lead = Lead(first_name=row['first_name'], last_name=row['last_name'],
                            email=row['email'], company_name=row['company_name'])
                lead.owner = current_user
                if form.lead_source.data:
                    lead.source = form.lead_source.data
                db.session.add(lead)
                ind = ind + 1

            db.session.commit()
            flash(f'{ind} new lead(s) has been successfully imported!', 'success')
        else:
            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("leads/leads_import.html", title="Import Leads", form=form)


@leads.route("/leads/reset_filters")
@login_required
@check_access('leads', 'view')
def reset_filters():
    reset_lead_filters()
    return redirect(url_for('leads.get_leads_view'))


@leads.route("/leads/bulk_owner_assign", methods=['POST'])
@login_required
@is_admin
def bulk_owner_assign():
    form = BulkOwnerAssign()

eeazycrm/templates/leads/lead_view.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ url_for('leads.update_lead', lead_id=lead.id) }}"
               class="btn btn-md btn-outline-primary mr-2" role="button">
                <span data-feather="edit-2"></span>
                  Edit
            </a>
            <a href="{{ url_for('leads.convert_lead', lead_id=lead.id) }}" class="btn btn-md btn-outline-primary mr-2" role="button">
                <span data-feather="arrow-left"></span>
                  Convert
            </a>
            <a href="{{ url_for('leads.get_leads_view') }}" class="btn btn-md btn-outline-secondary" role="button">
                <span data-feather="arrow-left"></span>
                  Back to View
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            <ul class="list-group list-group-flush">
                <li class="list-group-item g_field">
                  <div class="label">Title</div>
                  <div class="text">{{ lead.title if lead.title else '_' }}</div>
              </li>
              <li class="list-group-item g_field">
                  <div class="label">Name</div>
                  <div class="text">{{ lead.first_name if lead.first_name else '_' }} {{ lead.last_name if lead.last_name else '_' }}</div>
              </li>
                <li class="list-group-item g_field">
                  <div class="label">Email</div>
                    {% if lead.email %}
                        <div class="text">
                            <span data-feather="mail" class="mr-1"></span>
                            <a href="mailto: {{ lead.email }}">{{ lead.email }}</a>
                        </div>
                    {% else %}
                        <div class="text"><span data-feather="mail"></span> _</div>
                    {% endif %}
              </li>
                <li class="list-group-item g_field">
                  <div class="label">Company</div>
                  <div class="text">{{ lead.company_name if lead.company_name else '_' }}</div>
              </li>
                <li class="list-group-item g_field">
                  <div class="label">Lead Source</div>
                  <div class="text">{{ lead.source.source_name if lead.source else '_' }}</div>
              </li>
                <li class="list-group-item g_field">
                  <div class="label">Lead Status</div>
                  <div class="text">{{ lead.status.status_name if lead.status else '_' }}</div>
              </li>
                <li class="list-group-item g_field">
                  <div class="label">Owner</div>
                    {% if lead.owner %}
                    <div class="text">
                        <div class="mt-1">
                            {% with owner=lead.owner %}{% include 'common/owner_cell.html' %}{% endwith %}
                        </div>
                    </div>
                    {% else %}
                        <div class="text">_</div>
                    {% endif %}
              </li>
            </ul>
        </div>
        <div class="col-5">
            <ul class="list-group list-group-flush">
                <li class="list-group-item g_field col-12">
                  <div class="label">Address</div>
                  <div class="text">{{ lead.address_line if lead.address_line else '_' }}</div>
              </li>
              <li class="list-group-item g_field col-12">
                  <div class="row">
                      <div class="col-6">
                          <div class="label">State</div>
                          <div class="text">{{ lead.addr_state if lead.addr_state else '_' }}</div>
                      </div>
                      <div class="col-6">
                          <div class="label">City</div>
                          <div class="text">{{ lead.addr_city if lead.addr_city else '_' }}</div>
                      </div>
                  </div>
              </li>
                <li class="list-group-item g_field col-12">
                    <div class="row">
                        <div class="col-6">
                            <div class="label">Postcode</div>
                            <div class="text">{{ lead.post_code if lead.post_code else '_' }}</div>
                        </div>
                        <div class="col-6">
                            <div class="label">Country</div>
                            <div class="text">{{ lead.country if lead.country else '_' }}</div>
                        </div>
                    </div>
              </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-10">
            <div></div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item g_field col-12">
                    <div class="label">Notes</div>
                    <div class="text">{{ lead.notes if lead.notes else '_' }}</div>
                </li>
            </ul>
        </div>
    </div>
    {% endblock %}

eeazycrm/templates/leads/leads_list.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">

            <div class="dropdown">
              <button class="btn btn-sm btn-outline-primary mr-2 dropdown-toggle bulk_assign disabled"
                      type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                      aria-expanded="false">
                  <span data-feather="settings"></span> Bulk Actions
              </button>
              <div class="dropdown-menu dd-sm" aria-labelledby="dropdownMenuButton">
                  {% if current_user.is_admin %}
                <a class="dropdown-item " href="#" data-toggle="modal" data-target="#leadOwnerAssignModal">Assign Owner</a>
                  <a class="dropdown-item" href="#" data-toggle="modal" data-target="#leadSourceAssignModal">Assign Source</a>
                  <a class="dropdown-item" href="#" data-toggle="modal" data-target="#leadStatusAssignModal">Assign Status</a>
                    <div class="dropdown-divider"></div>
                  <a class="dropdown-item" data-toggle="modal" data-target="#leadsDeleteModal" href="#">Delete</a>
                  <div class="dropdown-divider"></div>
                  {% endif %}
                <a class="dropdown-item" id="export_leads_to_csv" href="#">Export to CSV</a>
              </div>
            </div>

            {% if current_user.is_admin %}
            <a class="btn btn-sm btn-outline-secondary mr-2" role="button" href="{{ url_for('leads.import_bulk_leads') }}">
                <span data-feather="upload"></span>
                  import leads ...
            </a>
            {% endif %}
            <a class="btn btn btn-sm btn-outline-primary" role="button" href="{{ url_for('leads.new_lead') }}">
                <span data-feather="plus"></span>
                  New
            </a>
        </div>
    </div>
    {% include "leads/filters.html" %}
    {% if leads.items()|length > 0 %}
        <div class="table-responsive">
            <table class="table table-striped table-hover fixed-layout-table">
              <thead class="thead-light">
                <tr>
                  <th width="40" scope="col">
                      <input type="checkbox" id="select_all" value="all" />
                  </th>
                    <th width="150"></th>
                    <th width="300" scope="col">Title</th>
                  <th width="150" scope="col">First Name</th>
                  <th width="150" scope="col">Last Name</th>
                  <th width="300" scope="col">Email</th>
                    <th width="250" scope="col">Company Name</th>
                     <th width="150" scope="col">Phone</th>
                     <th width="150" scope="col">Mobile</th>
                    <th width="250" scope="col">Owner</th>
                    <th width="200" scope="col">Lead Source</th>
                     <th width="200" scope="col">Lead Status</th>
                    <th width="200" scope="col">Date Created</th>
                </tr>
              </thead>
              <tbody>
                {% for lead in leads.items() %}
                <tr>
                  <th scope="row">
                      <input class="cb" type="checkbox" value="{{ lead.id }}" />
                  </th>
                    <th>
                        <a href="{{ url_for('leads.update_lead', lead_id=lead.id) }}"
                           class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="edit"></span>
                        </a>
                        <a href="#" data-toggle="modal" data-target="#singleLeadDeleteModal_{{ lead.id }}"
                           class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="trash"></span>
                        </a>
                        {% with lead_id=lead.id %}
                            {% include 'leads/single_lead_delete_modal.html' %}
                        {% endwith %}
                        <a href="{{ url_for('leads.get_lead_view', lead_id=lead.id) }}"
                           class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="arrow-up-right"></span>
                        </a>
                    </th>
                    <td>{{ lead.title }}</td>
                  <td>{{ lead.first_name }}</td>
                  <td>{{ lead.last_name }}</td>
                    <td>{{ lead.email }}</td>
                    <td>{{ lead.company_name }}</td>
                    <td>{{ lead.phone }}</td>
                    <td>{{ lead.mobile }}</td>
                    <td>{% with owner=lead.owner %}{% include 'common/owner_cell.html' %}{% endwith %}</td>
                    <td>{{ lead.source.source_name }}</td>
                    <td>{{ lead.status.status_name }}</td>
                    <td>{{ lead.date_created.strftime('%Y-%m-%d') if lead.date_created }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>

        <!-- pagination -->
        {% if leads.total_records > 10 %}
            {% with view_id="leads.get_leads_view", items=leads %}
                {% include "common/pagination.html" %}
            {% endwith %}
        {% endif %}
    {% else %}
        <div class="container text-center pt-4">
            <div><span data-feather="eye-off"></span></div>
            <p>No leads found. Please create your first lead.</p>
        </div>
    {%  endif %}
<script>
    $(document).ready(function() {
        var items = [];

        $('#select_all').on('click', function() {
            if ($(this).is(':checked')) {
                $('.cb').prop('checked', true);
            } else {
                $('.cb').prop('checked', false);
            }
            toggle_convert_lead_btn();
        });

        $('.cb').on('click', function() {
            toggle_convert_lead_btn();
        });

        function toggle_convert_lead_btn() {
            items = [];
            $('.cb').each(function() {
                if ($(this).is(':checked')) {
                    items.push($(this).val());
                }
            });

            if (items.length > 0) {
                $('#convert_lead').removeClass('disabled');
                $('.bulk_assign').removeClass('disabled');
            } else {
                $('#convert_lead').addClass('disabled');
                $('.bulk_assign').addClass('disabled');
            }
        }

        $('.ba_modal').on('show.bs.modal', function (e) {
          // do something...
          $('.modal-notif-area').html(`
                <div class="alert alert-success" role="alert">
                  You have selected <strong>${items.length}</strong> leads for bulk assignment.
                </div>`);

          // store the values
          console.log(items);
          $('.leads_data').val(items);
        });

        $('#export_leads_to_csv').on('click', function(e) {
            e.preventDefault();
            window.location = "{{ url_for('leads.write_to_csv') }}?lead_ids=" + items
        });

    });
</script>

<!-- Lead Owner Assign Modal -->
{% include "leads/bulk_owner_assign_modal.html" %}

<!-- Lead Source Assign Modal -->
{% include "leads/bulk_lead_source_assign_modal.html" %}

<!-- Lead Status Assign Modal -->
{% include "leads/bulk_lead_status_assign_modal.html" %}

<!-- Lead Bulk Delete Modal -->
{% include "leads/bulk_lead_delete_modal.html" %}


{% endblock %}