eeazycrm/install/models.py
from eeazycrm import db


class User(db.Model):
    id = db.Column(db.Integer, db.Sequence('user_id_seq'), primary_key=True)
    first_name = db.Column(db.String(20), nullable=True)
    last_name = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    avatar = db.Column(db.String(25), nullable=True)
    password = db.Column(db.String(60), nullable=False)
    is_admin = db.Column(db.Boolean, nullable=False, default=False)
    is_first_login = db.Column(db.Boolean, nullable=False, default=True)
    is_user_active = db.Column(db.Boolean, nullable=False, default=False)

    def __repr__(self):
        return f"User('{self.first_name}', '{self.last_name}', '{self.email}')"

eeazycrm/deals/routes.py
from flask import Blueprint, session
from flask_login import current_user, login_required
from flask import render_template, flash, url_for, redirect, request
from sqlalchemy import or_
import json
from wtforms import Label

from eeazycrm import db
from .models import Deal, DealStage
from eeazycrm.common.paginate import Paginate
from eeazycrm.common.filters import CommonFilters
from eeazycrm.accounts.models import Account
from .forms import NewDeal, FilterDeals
from .filters import set_date_filters, set_price_filters, set_deal_stage_filters

from eeazycrm.rbac import check_access

deals = Blueprint('deals', __name__)


def reset_deal_filters():
    if 'deals_owner' in session:
        session.pop('deals_owner', None)
    if 'deals_search' in session:
        session.pop('deals_search', None)
    if 'deals_acc_owner' in session:
        session.pop('deals_acc_owner', None)
    if 'deals_contacts_owner' in session:
        session.pop('deals_contacts_owner', None)
    if 'deals_date_created' in session:
        session.pop('deals_date_created', None)
    if 'deal_price' in session:
        session.pop('deal_price', None)
    if 'deal_stage' in session:
        session.pop('deal_stage', None)


@deals.route("/deals", methods=['GET', 'POST'])
@login_required
@check_access('deals', 'view')
def get_deals_view():
    view_t = request.args.get('view_t', 'list', type=str)
    filters = FilterDeals()

    search = CommonFilters.set_search(filters, 'deals_search')
    owner = CommonFilters.set_owner(filters, 'Deal', 'deals_owner')
    account = CommonFilters.set_accounts(filters, 'Deal', 'deals_acc_owner')
    contact = CommonFilters.set_contacts(filters, 'Deal', 'deals_contacts_owner')
    advanced_filters = set_date_filters(filters, 'Deal', 'deals_date_created')
    price_filters = set_price_filters(filters, 'deal_price')
    deal_stage_filters = set_deal_stage_filters(filters, 'deal_stage')

    query = Deal.query.filter(or_(
        Deal.title.ilike(f'%{search}%')
    ) if search else True) \
        .filter(account) \
        .filter(contact) \
        .filter(price_filters) \
        .filter(deal_stage_filters) \
        .filter(owner) \
        .filter(advanced_filters) \
        .order_by(Deal.date_created.desc())

    if view_t == 'kanban':
        return render_template("deals/kanban_view.html", title="Deals View",
                               deals=query.all(),
                               deal_stages=DealStage.query.order_by(DealStage.display_order.asc()).all(),
                               filters=filters)
    else:
        return render_template("deals/deals_list.html", title="Deals View",
                               deals=Paginate(query), filters=filters)


@deals.route("/deals/<int:deal_id>")
@login_required
@check_access('deals', 'view')
def get_deal_view(deal_id):
    deal = Deal.query.filter_by(id=deal_id).first()
    print(deal.account, deal.contact)
    return render_template("deals/deal_view.html", title="Deal View", deal=deal)


@deals.route("/deals/new", methods=['GET', 'POST'])
@login_required
@check_access('deals', 'create')
def new_deal():
    account = request.args.get('acc', None, type=int)
    form = NewDeal()

    if account:
        form.accounts.data = Account.get_account(account)

    if request.method == 'POST':
        if form.validate_on_submit():
            deal = Deal(title=form.title.data,
                        expected_close_price=form.expected_close_price.data,
                        expected_close_date=form.expected_close_date.data,
                        notes=form.notes.data)

            deal.account = form.accounts.data
            if deal.account:
                deal.contact = form.contacts.data
            deal.dealstage = form.deal_stages.data

            if current_user.is_admin:
                deal.deal_owner = form.assignees.data
            else:
                deal.deal_owner = current_user

            db.session.add(deal)
            db.session.commit()
            flash('Deal has been successfully created!', 'success')
            return redirect(url_for('deals.get_deals_view'))
        else:
            for error in form.errors:
                print(error)
            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("deals/new_deal.html", title="New Deal", form=form)


@deals.route("/deals/edit/<int:deal_id>", methods=['GET', 'POST'])
@login_required
@check_access('deals', 'update')
def update_deal(deal_id):
    form = NewDeal()
    account = request.args.get('acc', None, type=int)
    if account:
        form.accounts.data = Account.get_account(account)

    deal = Deal.get_deal(deal_id)
    if not deal:
        return redirect(url_for('deals.get_deals_view'))

    if request.method == 'POST':
        if form.validate_on_submit():
            deal.title = form.title.data
            deal.expected_close_price = form.expected_close_price.data
            deal.expected_close_date = form.expected_close_date.data
            deal.deal_stage = form.deal_stages.data
            deal.deal_account = form.accounts.data
            if form.accounts.data:
                deal.contact = form.contacts.data

            if current_user.is_admin:
                deal.deal_owner = form.assignees.data

            deal.notes = form.notes.data
            db.session.commit()
            flash('The deal has been successfully updated', 'success')
            return redirect(url_for('deals.get_deal_view', deal_id=deal.id))
        else:
            print(form.errors)
            flash('Deal update failed! Form has errors', 'danger')
    elif request.method == 'GET':
        form.title.data = deal.title
        form.expected_close_price.data = deal.expected_close_price
        form.expected_close_date.data = deal.expected_close_date
        form.deal_stages.data = deal.deal_stage
        form.accounts.data = deal.account
        form.contacts.data = deal.contact
        print(deal.contact)
        form.assignees.data = deal.deal_owner
        form.notes.data = deal.notes
        form.submit.label = Label('update_deal', 'Update Deal')
    return render_template("deals/new_deal.html", title="Update Deal", form=form)


@deals.route("/deals/update_stage/<int:deal_id>/<int:stage_id>")
@login_required
@check_access('deals', 'update')
def update_deal_stage_ajax(deal_id, stage_id):
    deal = Deal.query.filter_by(id=deal_id).first()
    deal.deal_stage_id = stage_id
    db.session.commit()
    return json.dumps({'success': True, 'message': 'Done'})


@deals.route("/deals/reset_filters")
@login_required
@check_access('deals', 'view')
def reset_filters():
    reset_deal_filters()
    view_t = request.args.get('view_t', 'list', type=str)
    return redirect(url_for('deals.get_deals_view', view_t=view_t))

eeazycrm/leads/routes.py
import pandas as pd
from sqlalchemy import or_
from wtforms import Label

from flask import Blueprint, session, Response
from flask_login import current_user, login_required
from flask import render_template, flash, url_for, redirect, request

from eeazycrm import db
from .models import Lead
from eeazycrm.common.paginate import Paginate
from eeazycrm.common.filters import CommonFilters
from .filters import set_date_filters, set_source, set_status
from .forms import NewLead, ImportLeads, ConvertLead, \
    FilterLeads, BulkOwnerAssign, BulkLeadSourceAssign, BulkLeadStatusAssign, BulkDelete

from eeazycrm.rbac import check_access, is_admin

leads = Blueprint('leads', __name__)


def reset_lead_filters():
    if 'lead_owner' in session:
        session.pop('lead_owner', None)
    if 'lead_search' in session:
        session.pop('lead_search', None)
    if 'lead_date_created' in session:
        session.pop('lead_date_created', None)
    if 'lead_source' in session:
        session.pop('lead_source', None)
    if 'lead_status' in session:
        session.pop('lead_status', None)


@leads.route("/leads", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'view')
def get_leads_view():
    filters = FilterLeads()
    search = CommonFilters.set_search(filters, 'lead_search')
    owner = CommonFilters.set_owner(filters, 'Lead', 'lead_owner')
    advanced_filters = set_date_filters(filters, 'lead_date_created')
    source_filter = set_source(filters, 'lead_source')
    status_filter = set_status(filters, 'lead_status')

    query = Lead.query \
        .filter(or_(
            Lead.title.ilike(f'%{search}'),
            Lead.first_name.ilike(f'%{search}'),
            Lead.last_name.ilike(f'%{search}'),
            Lead.email.ilike(f'%{search}'),
            Lead.company_name.ilike(f'%{search}'),
            Lead.phone.ilike(f'%{search}'),
            Lead.mobile.ilike(f'%{search}'),
        ) if search else True) \
        .filter(source_filter) \
        .filter(status_filter) \
        .filter(owner) \
        .filter(advanced_filters) \
        .order_by(Lead.date_created.desc())

    bulk_form = {
        'owner': BulkOwnerAssign(),
        'lead_source': BulkLeadSourceAssign(),
        'lead_status': BulkLeadStatusAssign(),
        'delete': BulkDelete()
    }

    return render_template("leads/leads_list.html", title="Leads View",
                           leads=Paginate(query), filters=filters, bulk_form=bulk_form)


@leads.route("/leads/new", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'create')
def new_lead():
    form = NewLead()
    if request.method == 'POST':
        if form.validate_on_submit():
            lead = Lead(title=form.title.data,
                        first_name=form.first_name.data, last_name=form.last_name.data,
                        email=form.email.data, company_name=form.company.data,
                        address_line=form.address_line.data, addr_state=form.addr_state.data,
                        addr_city=form.addr_city.data, post_code=form.post_code.data,
                        country=form.country.data, source=form.lead_source.data,
                        status=form.lead_status.data, notes=form.notes.data)

            if current_user.is_admin:
                lead.owner = form.assignees.data
            else:
                lead.owner = current_user

            db.session.add(lead)
            db.session.commit()
            flash('New lead has been successfully created!', 'success')
            return redirect(url_for('leads.get_leads_view'))
        else:
            for error in form.errors:
                print(error)
            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("leads/new_lead.html", title="New Lead", form=form)


@leads.route("/leads/edit/<int:lead_id>", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'update')
def update_lead(lead_id):
    lead = Lead.get_by_id(lead_id)
    if not lead:
        return redirect(url_for('leads.get_leads_view'))

    form = NewLead()
    if request.method == 'POST':
        if form.validate_on_submit():
            lead.title = form.title.data
            lead.first_name = form.first_name.data
            lead.last_name = form.last_name.data
            lead.email = form.email.data
            lead.company_name = form.company.data
            lead.phone = form.phone.data
            lead.mobile = form.mobile.data
            lead.address_line = form.address_line.data
            lead.addr_state = form.addr_state.data
            lead.addr_city = form.addr_city.data
            lead.post_code = form.post_code.data
            lead.country = form.country.data
            lead.owner = form.assignees.data
            lead.source = form.lead_source.data
            lead.status = form.lead_status.data
            lead.notes = form.notes.data
            db.session.commit()
            flash('The lead has been successfully updated', 'success')
            return redirect(url_for('leads.get_lead_view', lead_id=lead.id))
        else:
            print(form.errors)
            flash('User update failed! Form has errors', 'danger')
    elif request.method == 'GET':
        form.title.data = lead.title
        form.first_name.data = lead.first_name
        form.last_name.data = lead.last_name
        form.email.data = lead.email
        form.company.data = lead.company_name
        form.phone.data = lead.phone
        form.mobile.data = lead.mobile
        form.address_line.data = lead.address_line
        form.addr_state.data = lead.addr_state
        form.addr_city.data = lead.addr_city
        form.post_code.data = lead.post_code
        form.country.data = lead.country
        form.assignees.data = lead.owner
        form.lead_source.data = lead.source
        form.lead_status.data = lead.status
        form.notes.data = lead.notes
        form.submit.label = Label('update_lead', 'Update Lead')
    return render_template("leads/new_lead.html", title="Update Lead", form=form)


@leads.route("/leads/<int:lead_id>")
@login_required
@check_access('leads', 'view')
def get_lead_view(lead_id):
    lead = Lead.query.filter_by(id=lead_id).first()
    return render_template("leads/lead_view.html", title="View Lead", lead=lead)


@leads.route("/leads/del/<int:lead_id>")
@login_required
@check_access('leads', 'remove')
def delete_lead(lead_id):
    lead = Lead.query.filter_by(id=lead_id).first()
    if not lead:
        flash('The lead does not exist', 'danger')
    else:
        Lead.query.filter_by(id=lead_id).delete()
        db.session.commit()
        flash('The lead has been removed successfully', 'success')
    return redirect(url_for('leads.get_leads_view'))


@leads.route("/leads/convert/<int:lead_id>", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'view')
@check_access('accounts', 'create')
@check_access('contacts', 'create')
@check_access('deals', 'create')
def convert_lead(lead_id):
    lead = Lead.query.filter_by(id=lead_id).first()
    form = ConvertLead()
    form.account_name.data = lead.company_name
    form.account_email.data = lead.email

    if request.method == 'POST':
        if form.validate_on_submit():
            if form.use_account_information.data and form.use_contact_information.data:
                # create both account and contact

                pass
            elif form.use_account_information.data and not form.use_contact_information.data:
                # create account only (and contact if chosen from dropdown)
                if not form.account_name.data:
                    form.account_name.errors = ['Please enter account name']
                if not form.account_name.data:
                    form.account_email.errors = ['Please enter account email']
            elif not form.use_account_information.data and form.use_contact_information.data:
                pass
                # create contact only (account dropdown must be selected)
            elif not form.use_account_information.data and not form.use_contact_information.data:
                # account must be selected in dropdown (and create contact if selected in dropdown)
                if not form.accounts.data:
                    form.accounts.errors = ['Please select an account']
                pass

            flash('Leads has been successfully converted!', 'success')
        else:
            flash('Your form has errors! Please check the fields', 'danger')
    else:
        form.title.data = lead.title
    return render_template("leads/lead_convert.html", title="Convert Lead", lead=lead, form=form)


@leads.route("/leads/import", methods=['GET', 'POST'])
@login_required
@is_admin
def import_bulk_leads():
    form = ImportLeads()
    if request.method == 'POST':
        ind = 0
        if form.validate_on_submit():
            data = pd.read_csv(form.csv_file.data)

            for _, row in data.iterrows():
                lead = Lead(first_name=row['first_name'], last_name=row['last_name'],
                            email=row['email'], company_name=row['company_name'])
                lead.owner = current_user
                if form.lead_source.data:
                    lead.source = form.lead_source.data
                db.session.add(lead)
                ind = ind + 1

            db.session.commit()
            flash(f'{ind} new lead(s) has been successfully imported!', 'success')
        else:
            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("leads/leads_import.html", title="Import Leads", form=form)


@leads.route("/leads/reset_filters")
@login_required
@check_access('leads', 'view')
def reset_filters():
    reset_lead_filters()
    return redirect(url_for('leads.get_leads_view'))


@leads.route("/leads/bulk_owner_assign", methods=['POST'])
@login_required
@is_admin
def bulk_owner_assign():
    form = BulkOwnerAssign()

eeazycrm/templates/deals/deal_view.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ url_for('deals.update_deal', deal_id=deal.id) }}"
               class="btn btn-md btn-outline-primary mr-2" role="button">
                <span data-feather="edit-2"></span>
                  Edit
            </a>
            <a href="{{ url_for('deals.get_deals_view') }}" class="btn btn-md btn-outline-secondary" role="button">
                <span data-feather="arrow-left"></span>
                  Back to List
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-10">
            <ul class="list-group list-group-flush">

                <li class="list-group-item g_field">
                  <div class="label"></div>
                    <div class="text">{{ deal.title if deal.title else '_' }}</div>
              </li>

                <li class="list-group-item g_field col-12">
                    <div class="row">
                      <div class="col-6">
                          <div class="label">Expected Close Price</div>
                          <div class="text">{{ deal.expected_close_price if deal.expected_close_price else '_' }}</div>
                      </div>
                      <div class="col-6">
                          <div class="label">Expected Close Date</div>
                          <div class="text">{{ deal.expected_close_date.strftime('%d %B, %Y') if deal.expected_close_date else '_' }}</div>
                      </div>
                  </div>
                </li>

                <li class="list-group-item g_field col-12">
                    <div class="row">
                      <div class="col-6">
                          <div class="label">Account</div>
                          <div class="text">
                              {{ deal.account.name }}
                          </div>
                      </div>
                      <div class="col-6">
                          <div class="label">Contact Name</div>
                          <div class="text">
                              <span data-feather="user" class="mr-1"></span> {{ deal.contact.get_contact_name() if deal.contact else '_' }}
                          </div>
                      </div>
                    </div>
              </li>

                <li class="list-group-item g_field">
                  <div class="label">Owner</div>
                    {% if deal.deal_owner %}
                    <div class="text">
                        <div class="mt-1">
                            {% with owner=deal.deal_owner %}{% include 'common/owner_cell.html' %}{% endwith %}
                        </div>
                    </div>
                    {% else %}
                        <div class="text">_</div>
                    {% endif %}
              </li>

                <li class="list-group-item g_field col-12">
                    <div class="label">Notes</div>
                    <div class="text">{{ deal.notes if deal.notes else '_' }}</div>
                </li>

            </ul>
        </div>
    </div>
    {% endblock %}

eeazycrm/templates/deals/deals_list.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a class="btn btn btn-sm btn-outline-primary mr-2" role="button" href="{{ url_for('deals.get_deals_view') }}?view_t=kanban">
                <span data-feather="trello"></span>
            </a>
            {% if current_user.is_admin %}
            <a class="btn btn-sm btn-outline-secondary mr-2" role="button" href="{{ url_for('leads.import_bulk_leads') }}">
                <span data-feather="upload"></span>
                  import deals ...
            </a>
            {% endif %}
            <a class="btn btn btn-sm btn-outline-primary" role="button" href="{{ url_for('deals.new_deal') }}">
                <span data-feather="plus"></span>
                  New
            </a>
        </div>
    </div>
    {% include "deals/filters.html" %}
    {% if deals.items()|length > 0 %}
        <div class="table-responsive">
            <table class="table table-striped table-hover fixed-layout-table">
              <thead class="thead-light">
                <tr>
                  <th width="40" scope="col">
                      <input type="checkbox" id="select_all" value="all" />
                  </th>
                    <th width="250"></th>
                    <th width="350" scope="col">Title</th>
                  <th width="200" scope="col">Expected Close Price</th>
                  <th width="200" scope="col">Expected Close Date</th>
                  <th width="300" scope="col">Account</th>
                    <th width="250" scope="col">Contact</th>
                    <th width="200" scope="col">Deal Stage</th>
                    <th width="250" scope="col">Owner</th>
                    <th width="200" scope="col">Date Created</th>
                </tr>
              </thead>
              <tbody>
                {% for deal in deals.items() %}
                <tr>
                  <th scope="row">
                      <input class="cb" type="checkbox" value="{{ deal.id }}" />
                  </th>
                    <th>
                        <a href="{{ url_for('deals.update_deal', deal_id=deal.id) }}" class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="edit"></span>
                        </a>
                        <a href="#" class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="trash"></span>
                        </a>
                        <a href="{{ url_for('deals.get_deal_view', deal_id=deal.id) }}"
                           class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="arrow-up-right"></span>
                        </a>
                    </th>
                    <td>{{ deal.title }}</td>
                  <td>{{ config.def_currency.symbol }} {{ "{:,.2f}".format(deal.expected_close_price) }}</td>
                    <td>{% if deal.is_expired() %}<span class="icon-warning" data-feather="alert-circle"></span>{%endif%}
                        {{ deal.expected_close_date.strftime('%Y-%m-%d %I:%M %p').lower() if deal.expected_close_date }}</td>
                    <td>{{ deal.account.name }}</td>
                    <td>{{ deal.contact.first_name }} {{ deal.contact.last_name }}</td>
                     <td>{{ deal.dealstage.stage_name }}</td>
                    <td>{% with owner=deal.deal_owner %}{% include 'common/owner_cell.html' %}{% endwith %}</td>
                    <td>{{ deal.date_created.strftime('%Y-%m-%d') if deal.date_created }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>

        <!-- pagination -->
        {% if deals.total_records > 10 %}
            {% with view_id="deals.get_deals_view", items=deals %}
                {% include "common/pagination.html" %}
            {% endwith %}
        {% endif %}
    {% else %}
        <div class="container text-center pt-4">
            <div><span data-feather="eye-off"></span></div>
            <p>No deals found. Please create your first deal.</p>
        </div>
    {%  endif %}
<script>
    $(document).ready(function() {
        $('#select_all').on('click', function() {
            if ($(this).is(':checked')) {
                $('.cb').prop('checked', true);
            } else {
                $('.cb').prop('checked', false);
            }
        });
    });
</script>
{% endblock %}

eeazycrm/templates/deals/kanban_view.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a class="btn btn btn-sm btn-outline-primary mr-2" role="button" href="{{ url_for('deals.get_deals_view') }}">
                <span data-feather="list"></span>
            </a>
            {% if current_user.is_admin %}
            <a class="btn btn-sm btn-outline-secondary mr-2" role="button" href="{{ url_for('leads.import_bulk_leads') }}">
                <span data-feather="upload"></span>
                  import deals ...
            </a>
            {% endif %}
            <a class="btn btn btn-sm btn-outline-primary" role="button" href="{{ url_for('deals.new_deal') }}">
                <span data-feather="plus"></span>
                  New
            </a>
        </div>
    </div>
    {% include "deals/kanban_filters.html" %}
    {% if deals|length > 0 %}
        <div class="container-fluid" style="background-color: #f1f1f1; padding: 20px;">
            <div class="kanban-container">
                {% for stage_item in deal_stages %}

                <div class="card outer-card">
                  <div id="cb_{{ stage_item.id }}" class="card-body"
                       data-dropstage="{{ stage_item.id }}" ondrop="drop(event)" ondragover="allowDrop(event)">
                    <h5 class="card-title">{{ stage_item.stage_name }}</h5>
                      {% for deal in deals %}
                        {% if deal.dealstage.stage_name == stage_item.stage_name %}

                            <div id="item_{{ deal.id }}" data-dealid="{{ deal.id }}" class="card inner-card bg-light mb-3"
                                 draggable="true" ondragstart="dragStart(event)">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <div class="text">{{ deal.title|truncate(35, True)}}</div>
                                    </h5>
                                    <div class="card-text">
                                        <div class="price">{{ config.def_currency.symbol }} {{ "{:,.2f}".format(deal.expected_close_price) }}</div>
                                        <div>{{ deal.account.name }}</div>
                                        <div><span data-feather="user"></span> {{ deal.contact.first_name }} {{ deal.contact.last_name }}</div>
                                        <div><span data-feather="clock"></span> {% if deal.is_expired() %}<span class="icon-warning" data-feather="alert-circle"></span>{%endif%} {{ deal.expected_close_date.strftime('%Y-%m-%d') if deal.expected_close_date else '_' }}</div>
                                    </div>
                                    <div class="card-actions">
                                        <div class="ca_item">
                                            <a href="#" class="btn btn-sm btn-outline-secondary" role="button">
                                                <span data-feather="arrow-up-right"></span> view details
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endif %}
                      {% endfor %}

                  </div>
                </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class="container text-center pt-4">
            <div><span data-feather="eye-off"></span></div>
            <p>No deals found. Please create your first deal.</p>
        </div>
    {%  endif %}
<script>
    function allowDrop(ev) {
      ev.preventDefault();
      ev.stopPropagation();
    }

    function update_deal_stage(dealId, dealStageId) {

        $('.ajax_indicator')
            .css('display', 'block')
            .text('processing')
            .removeClass('done')
            .addClass('processing');

        $.ajax({
            type: "GET",
            url: "/deals/update_stage/" + dealId + "/" + dealStageId,
            contentType: 'application/json',
            dataType: 'json',
            success: function(data) {
                $('.ajax_indicator')
                    .html("<span data-feather='check'></span> " + data.message)
                    .removeClass('processing')
                    .addClass('done')
                    .fadeOut(2000);

            },
        });
    }

    function drop(ev) {
      ev.preventDefault();
      var data = ev.dataTransfer.getData("text");
      var node = document.getElementById(data);
      var first_node = ev.currentTarget.children[1];
      if (node.parentNode.id !== ev.currentTarget.id) {
        ev.currentTarget.insertBefore(node, first_node);
        update_deal_stage(node.dataset.dealid, ev.currentTarget.dataset.dropstage);
      }
      node.style.transform = 'rotate(0deg)';
    }

    function dragStart(ev) {
      ev.dataTransfer.effectAllowed = "move";
      ev.dataTransfer.setData("text/plain", ev.target.id);
      ev.currentTarget.style.transform = 'rotate(3deg)';
    }
</script>
    {% endblock %}