eeazycrm/accounts/routes.py
from flask import Blueprint, session
from flask_login import current_user, login_required
from flask import render_template, flash, url_for, redirect, request
from sqlalchemy import or_, text
from datetime import date, timedelta

from eeazycrm import db
from .models import Account
from eeazycrm.common.paginate import Paginate
from eeazycrm.common.filters import CommonFilters
from .forms import NewAccount, FilterAccounts, filter_accounts_adv_filters_query

from eeazycrm.rbac import check_access
from wtforms import Label

accounts = Blueprint('accounts', __name__)


def set_filters(f_id, module):
    today = date.today()
    filter_d = True
    if f_id == 1:
        filter_d = text("Account.is_active=True")
    elif f_id == 2:
        filter_d = text("Account.is_active=False")
    elif f_id == 3:
        filter_d = text("Date(%s.date_created)='%s'" % (module, today))
    elif f_id == 4:
        filter_d = text("Date(%s.date_created)='%s'" % (module, (today - timedelta(1))))
    elif f_id == 5:
        filter_d = text("Date(%s.date_created) > current_date - interval '7' day" % module)
    elif f_id == 6:
        filter_d = text("Date(%s.date_created) > current_date - interval '30' day" % module)
    return filter_d


def set_date_filters(filters, module, key):
    filter_d = True
    if request.method == 'POST':
        if filters.advanced_user.data:
            filter_d = set_filters(filters.advanced_user.data['id'], module)
            session[key] = filters.advanced_user.data['id']
    else:
        if key in session:
            filter_d = set_filters(session[key], module)
            filters.advanced_user.data = filter_accounts_adv_filters_query()[session[key] - 1]
    return filter_d


def reset_accounts_filters():
    if 'accounts_owner' in session:
        session.pop('accounts_owner', None)
    if 'accounts_search' in session:
        session.pop('accounts_search', None)
    if 'account_active' in session:
        session.pop('account_active', None)
    if 'accounts_date_created' in session:
        session.pop('accounts_date_created', None)


@accounts.route("/accounts", methods=['GET', 'POST'])
@login_required
@check_access('accounts', 'view')
def get_accounts_view():
    filters = FilterAccounts()
    search = CommonFilters.set_search(filters, 'accounts_search')
    owner = CommonFilters.set_owner(filters, 'Account', 'accounts_owner')
    advanced_filters = set_date_filters(filters, 'Account', 'accounts_date_created')

    query = Account.query.filter(or_(
        Account.name.ilike(f'%{search}%'),
        Account.website.ilike(f'%{search}%'),
        Account.email.ilike(f'%{search}%'),
        Account.phone.ilike(f'%{search}%'),
        Account.address_line.ilike(f'%{search}%'),
        Account.addr_state.ilike(f'%{search}%'),
        Account.addr_city.ilike(f'%{search}%'),
        Account.post_code.ilike(f'%{search}%')
    ) if search else True) \
        .filter(owner) \
        .filter(advanced_filters) \
        .order_by(Account.date_created.desc())

    return render_template("accounts/accounts_list.html", title="Accounts View",
                           accounts=Paginate(query=query), filters=filters)


@accounts.route("/accounts/edit/<int:account_id>", methods=['GET', 'POST'])
@login_required
@check_access('accounts', 'update')
def update_account(account_id):
    account = Account.get_account(account_id)
    if not account:
        return redirect(url_for('accounts.get_accounts_view'))

    form = NewAccount()
    if request.method == 'POST':
        if form.validate_on_submit():
            account.name = form.name.data
            account.website = form.website.data
            account.email = form.email.data
            account.phone = form.phone.data
            account.address_line = form.address_line.data
            account.addr_state = form.addr_state.data
            account.addr_city = form.addr_city.data
            account.post_code = form.post_code.data
            account.country = form.country.data
            account.account_owner = form.assignees.data
            account.notes = form.notes.data
            db.session.commit()
            flash('The account has been successfully updated', 'success')
            return redirect(url_for('accounts.get_account_view', account_id=account.id))
        else:
            print(form.errors)
            flash('Accounts update failed! Form has errors', 'danger')
    elif request.method == 'GET':
        form.name.data = account.name
        form.website.data = account.website
        form.email.data = account.email
        form.phone.data = account.phone
        form.address_line.data = account.address_line
        form.addr_state.data = account.addr_state
        form.addr_city.data = account.addr_city
        form.post_code.data = account.post_code
        form.country.data = account.country
        form.assignees.data = account.account_owner
        form.notes.data = account.notes
        form.submit.label = Label('update_account', 'Update Account')
    return render_template("accounts/new_account.html", title="Update Account", form=form)


@accounts.route("/accounts/<int:account_id>")
@login_required
@check_access('accounts', 'view')
def get_account_view(account_id):
    account = Account.query.filter_by(id=account_id).first()
    return render_template("accounts/account_view.html", title="View Account", account=account)


@accounts.route("/accounts/new", methods=['GET', 'POST'])
@login_required
@check_access('accounts', 'create')
def new_account():
    form = NewAccount()
    if request.method == 'POST':
        if form.validate_on_submit():
            account = Account(name=form.name.data,
                              website=form.website.data,
                              email=form.email.data,
                              phone=form.phone.data,
                              address_line=form.address_line.data,
                              addr_state=form.addr_state.data,
                              addr_city=form.addr_city.data,
                              post_code=form.post_code.data,
                              country=form.country.data,
                              notes=form.notes.data)

            if current_user.is_admin:
                account.account_owner = form.assignees.data
            else:
                account.account_owner = current_user

            db.session.add(account)
            db.session.commit()
            flash('Account has been successfully created!', 'success')
            return redirect(url_for('accounts.get_accounts_view'))
        else:
            for error in form.errors:
                print(error)
            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("accounts/new_account.html", title="New Account", form=form)


@accounts.route("/accounts/del/<int:account_id>")
@login_required
@check_access('accounts', 'delete')
def delete_account(account_id):
    Account.query.filter_by(id=account_id).delete()
    db.session.commit()
    flash('Account removed successfully!', 'success')
    return redirect(url_for('accounts.get_accounts_view'))


@accounts.route("/accounts/reset_filters")
@login_required
@check_access('accounts', 'view')
def reset_filters():
    reset_accounts_filters()
    return redirect(url_for('accounts.get_accounts_view'))

eeazycrm/leads/routes.py
import pandas as pd
from sqlalchemy import or_
from wtforms import Label

from flask import Blueprint, session, Response
from flask_login import current_user, login_required
from flask import render_template, flash, url_for, redirect, request

from eeazycrm import db
from .models import Lead
from eeazycrm.common.paginate import Paginate
from eeazycrm.common.filters import CommonFilters
from .filters import set_date_filters, set_source, set_status
from .forms import NewLead, ImportLeads, ConvertLead, \
    FilterLeads, BulkOwnerAssign, BulkLeadSourceAssign, BulkLeadStatusAssign, BulkDelete

from eeazycrm.rbac import check_access, is_admin

leads = Blueprint('leads', __name__)


def reset_lead_filters():
    if 'lead_owner' in session:
        session.pop('lead_owner', None)
    if 'lead_search' in session:
        session.pop('lead_search', None)
    if 'lead_date_created' in session:
        session.pop('lead_date_created', None)
    if 'lead_source' in session:
        session.pop('lead_source', None)
    if 'lead_status' in session:
        session.pop('lead_status', None)


@leads.route("/leads", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'view')
def get_leads_view():
    filters = FilterLeads()
    search = CommonFilters.set_search(filters, 'lead_search')
    owner = CommonFilters.set_owner(filters, 'Lead', 'lead_owner')
    advanced_filters = set_date_filters(filters, 'lead_date_created')
    source_filter = set_source(filters, 'lead_source')
    status_filter = set_status(filters, 'lead_status')

    query = Lead.query \
        .filter(or_(
            Lead.title.ilike(f'%{search}'),
            Lead.first_name.ilike(f'%{search}'),
            Lead.last_name.ilike(f'%{search}'),
            Lead.email.ilike(f'%{search}'),
            Lead.company_name.ilike(f'%{search}'),
            Lead.phone.ilike(f'%{search}'),
            Lead.mobile.ilike(f'%{search}'),
        ) if search else True) \
        .filter(source_filter) \
        .filter(status_filter) \
        .filter(owner) \
        .filter(advanced_filters) \
        .order_by(Lead.date_created.desc())

    bulk_form = {
        'owner': BulkOwnerAssign(),
        'lead_source': BulkLeadSourceAssign(),
        'lead_status': BulkLeadStatusAssign(),
        'delete': BulkDelete()
    }

    return render_template("leads/leads_list.html", title="Leads View",
                           leads=Paginate(query), filters=filters, bulk_form=bulk_form)


@leads.route("/leads/new", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'create')
def new_lead():
    form = NewLead()
    if request.method == 'POST':
        if form.validate_on_submit():
            lead = Lead(title=form.title.data,
                        first_name=form.first_name.data, last_name=form.last_name.data,
                        email=form.email.data, company_name=form.company.data,
                        address_line=form.address_line.data, addr_state=form.addr_state.data,
                        addr_city=form.addr_city.data, post_code=form.post_code.data,
                        country=form.country.data, source=form.lead_source.data,
                        status=form.lead_status.data, notes=form.notes.data)

            if current_user.is_admin:
                lead.owner = form.assignees.data
            else:
                lead.owner = current_user

            db.session.add(lead)
            db.session.commit()
            flash('New lead has been successfully created!', 'success')
            return redirect(url_for('leads.get_leads_view'))
        else:
            for error in form.errors:
                print(error)
            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("leads/new_lead.html", title="New Lead", form=form)


@leads.route("/leads/edit/<int:lead_id>", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'update')
def update_lead(lead_id):
    lead = Lead.get_by_id(lead_id)
    if not lead:
        return redirect(url_for('leads.get_leads_view'))

    form = NewLead()
    if request.method == 'POST':
        if form.validate_on_submit():
            lead.title = form.title.data
            lead.first_name = form.first_name.data
            lead.last_name = form.last_name.data
            lead.email = form.email.data
            lead.company_name = form.company.data
            lead.phone = form.phone.data
            lead.mobile = form.mobile.data
            lead.address_line = form.address_line.data
            lead.addr_state = form.addr_state.data
            lead.addr_city = form.addr_city.data
            lead.post_code = form.post_code.data
            lead.country = form.country.data
            lead.owner = form.assignees.data
            lead.source = form.lead_source.data
            lead.status = form.lead_status.data
            lead.notes = form.notes.data
            db.session.commit()
            flash('The lead has been successfully updated', 'success')
            return redirect(url_for('leads.get_lead_view', lead_id=lead.id))
        else:
            print(form.errors)
            flash('User update failed! Form has errors', 'danger')
    elif request.method == 'GET':
        form.title.data = lead.title
        form.first_name.data = lead.first_name
        form.last_name.data = lead.last_name
        form.email.data = lead.email
        form.company.data = lead.company_name
        form.phone.data = lead.phone
        form.mobile.data = lead.mobile
        form.address_line.data = lead.address_line
        form.addr_state.data = lead.addr_state
        form.addr_city.data = lead.addr_city
        form.post_code.data = lead.post_code
        form.country.data = lead.country
        form.assignees.data = lead.owner
        form.lead_source.data = lead.source
        form.lead_status.data = lead.status
        form.notes.data = lead.notes
        form.submit.label = Label('update_lead', 'Update Lead')
    return render_template("leads/new_lead.html", title="Update Lead", form=form)


@leads.route("/leads/<int:lead_id>")
@login_required
@check_access('leads', 'view')
def get_lead_view(lead_id):
    lead = Lead.query.filter_by(id=lead_id).first()
    return render_template("leads/lead_view.html", title="View Lead", lead=lead)


@leads.route("/leads/del/<int:lead_id>")
@login_required
@check_access('leads', 'remove')
def delete_lead(lead_id):
    lead = Lead.query.filter_by(id=lead_id).first()
    if not lead:
        flash('The lead does not exist', 'danger')
    else:
        Lead.query.filter_by(id=lead_id).delete()
        db.session.commit()
        flash('The lead has been removed successfully', 'success')
    return redirect(url_for('leads.get_leads_view'))


@leads.route("/leads/convert/<int:lead_id>", methods=['GET', 'POST'])
@login_required
@check_access('leads', 'view')
@check_access('accounts', 'create')
@check_access('contacts', 'create')
@check_access('deals', 'create')
def convert_lead(lead_id):
    lead = Lead.query.filter_by(id=lead_id).first()
    form = ConvertLead()
    form.account_name.data = lead.company_name
    form.account_email.data = lead.email

    if request.method == 'POST':
        if form.validate_on_submit():
            if form.use_account_information.data and form.use_contact_information.data:
                # create both account and contact

                pass
            elif form.use_account_information.data and not form.use_contact_information.data:
                # create account only (and contact if chosen from dropdown)
                if not form.account_name.data:
                    form.account_name.errors = ['Please enter account name']
                if not form.account_name.data:
                    form.account_email.errors = ['Please enter account email']
            elif not form.use_account_information.data and form.use_contact_information.data:
                pass
                # create contact only (account dropdown must be selected)
            elif not form.use_account_information.data and not form.use_contact_information.data:
                # account must be selected in dropdown (and create contact if selected in dropdown)
                if not form.accounts.data:
                    form.accounts.errors = ['Please select an account']
                pass

            flash('Leads has been successfully converted!', 'success')
        else:
            flash('Your form has errors! Please check the fields', 'danger')
    else:
        form.title.data = lead.title
    return render_template("leads/lead_convert.html", title="Convert Lead", lead=lead, form=form)


@leads.route("/leads/import", methods=['GET', 'POST'])
@login_required
@is_admin
def import_bulk_leads():
    form = ImportLeads()
    if request.method == 'POST':
        ind = 0
        if form.validate_on_submit():
            data = pd.read_csv(form.csv_file.data)

            for _, row in data.iterrows():
                lead = Lead(first_name=row['first_name'], last_name=row['last_name'],
                            email=row['email'], company_name=row['company_name'])
                lead.owner = current_user
                if form.lead_source.data:
                    lead.source = form.lead_source.data
                db.session.add(lead)
                ind = ind + 1

            db.session.commit()
            flash(f'{ind} new lead(s) has been successfully imported!', 'success')
        else:
            flash('Your form has errors! Please check the fields', 'danger')
    return render_template("leads/leads_import.html", title="Import Leads", form=form)


@leads.route("/leads/reset_filters")
@login_required
@check_access('leads', 'view')
def reset_filters():
    reset_lead_filters()
    return redirect(url_for('leads.get_leads_view'))


@leads.route("/leads/bulk_owner_assign", methods=['POST'])
@login_required
@is_admin
def bulk_owner_assign():
    form = BulkOwnerAssign()

eeazycrm/templates/accounts/account_view.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ url_for('accounts.update_account', account_id=account.id) }}"
               class="btn btn-md btn-outline-primary mr-2" role="button">
                <span data-feather="edit-2"></span>
                  Edit
            </a>
            <a href="#" class="btn btn-md btn-outline-secondary mr-2" data-toggle="modal" data-target="#viewContactsModal" role="button">
                <span data-feather="users"></span>
                  View Contacts
            </a>
            <a href="{{ url_for('accounts.get_accounts_view') }}" class="btn btn-md btn-outline-secondary" role="button">
                <span data-feather="arrow-left"></span>
                  Back to List
            </a>
        </div>
    </div>

    <!-- Modal -->
                <div class="modal fade" id="viewContactsModal" tabindex="-1" role="dialog" aria-labelledby="viewContactsModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Contacts</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body text-center">
                        {% if account.contacts|length > 0 %}
                          <div class="mt-2 mb-4">Contacts of <strong>{{ account.name }}</strong></div>
                          <table class="table table-striped table-hover">
                            <thead class="thead-light">
                                <tr>
                                    <th>Contact Name</th>
                                    <th>Contact Email</th>
                                </tr>
                            </thead>
                              <tbody>
                                {% for contact in account.contacts %}
                                    <tr>
                                        <td>{{ contact.first_name }} {{ contact.last_name }}</td>
                                        <td>{{ contact.email }}</td>
                                    </tr>
                                {% endfor %}
                              </tbody>
                          </table>
                          {% else %}
                          <div class="mt-4 mb-4">No contacts have been created for <strong>{{ account.name }}</strong></div>
                          <a href="#" class="btn btn-md btn-outline-primary mb-4" role="button">
                              <span data-feather="users"></span> Create New Contact
                          </a>
                          {% endif %}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>

    <div class="row">
        <div class="col-5">
            <ul class="list-group list-group-flush">
                <li class="list-group-item g_field">
                  <div class="label">Account Name</div>
                  <div class="text">{{ account.name if account.name else '_' }}</div>
              </li>
                <li class="list-group-item g_field">
                  <div class="label">Email</div>
                    {% if account.email %}
                        <div class="text">
                            <span data-feather="mail" class="mr-1"></span>
                            <a href="mailto: {{ account.email }}">{{ account.email }}</a>
                        </div>
                    {% else %}
                        <div class="text"><span data-feather="mail"></span> _</div>
                    {% endif %}
              </li>
              <li class="list-group-item g_field">
                  <div class="label">Website</div>
                  {% if account.website %}
                  <div class="text">
                      <span data-feather="globe" class="mr-1"></span>
                      <a href="{{ account.website }}" target="_blank">{{ account.website }}</a>
                  </div>
                  {% else %}
                    <div class="text"><span data-feather="globe"></span> _</div>
                  {% endif %}
              </li>

                <li class="list-group-item g_field">
                  <div class="label">Phone</div>
                  <div class="text"><span data-feather="phone" class="mr-1"></span> {{ account.phone if account.phone else '_' }}</div>
              </li>

                <li class="list-group-item g_field">
                  <div class="label">Owner</div>
                    {% if account.account_owner %}
                    <div class="text">
                        <div class="mt-1">
                            {% with owner=account.account_owner %}{% include 'common/owner_cell.html' %}{% endwith %}
                        </div>
                    </div>
                    {% else %}
                        <div class="text">_</div>
                    {% endif %}
              </li>

            </ul>
        </div>
        <div class="col-5">
            <ul class="list-group list-group-flush">
                <li class="list-group-item g_field col-12">
                  <div class="label">Address</div>
                  <div class="text">{{ account.address_line if account.address_line else '_' }}</div>
              </li>
              <li class="list-group-item g_field col-12">
                  <div class="row">
                      <div class="col-6">
                          <div class="label">State</div>
                          <div class="text">{{ account.addr_state if account.addr_state else '_' }}</div>
                      </div>
                      <div class="col-6">
                          <div class="label">City</div>
                          <div class="text">{{ account.addr_city if account.addr_city else '_' }}</div>
                      </div>
                  </div>
              </li>
                <li class="list-group-item g_field col-12">
                    <div class="row">
                        <div class="col-6">
                            <div class="label">Postcode</div>
                            <div class="text">{{ account.post_code if account.post_code else '_' }}</div>
                        </div>
                        <div class="col-6">
                            <div class="label">Country</div>
                            <div class="text">{{ account.country if account.country else '_' }}</div>
                        </div>
                    </div>
              </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-10">
            <div></div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item g_field col-12">
                    <div class="label">Notes</div>
                    <div class="text">{{ account.notes if account.notes else '_' }}</div>
                </li>
            </ul>
        </div>
    </div>
    {% endblock %}

eeazycrm/templates/accounts/accounts_list.html
{% extends "layout.html" %}
    {% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h4">{% if title %}{{title}}{% else %}No Title{% endif %}</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            {% if current_user.is_admin %}
            <a class="btn btn-sm btn-outline-secondary mr-2" role="button" href="{{ url_for('leads.import_bulk_leads') }}">
                <span data-feather="upload"></span>
                  import accounts ...
            </a>
            {% endif %}
            <a class="btn btn btn-sm btn-outline-primary" role="button" href="{{ url_for('accounts.new_account') }}">
                <span data-feather="plus"></span>
                  New
            </a>
        </div>
    </div>
    {% include "accounts/filters.html" %}
    {% if accounts.items()|length > 0 %}
        <div class="table-responsive">
            <table class="table table-striped table-hover fixed-layout-table">
              <thead class="thead-light">
                <tr>
                  <th width="40" scope="col">
                      <input type="checkbox" id="select_all" value="all" />
                  </th>
                    <th width="150"></th>
                    <th width="300" scope="col">Account Name</th>
                  <th width="250" scope="col">Email</th>
                  <th width="150" scope="col">Website</th>
                  <th width="150" scope="col">Phone</th>
                    <th width="250" scope="col">Address</th>
                    <th width="250" scope="col">State</th>
                    <th width="200" scope="col">City</th>
                    <th width="100" scope="col">Pincode</th>
                    <th width="100" scope="col">Country</th>
                    <th width="100" scope="col">Is Active</th>
                    <th width="200" scope="col">Owner</th>
                    <th width="200" scope="col">Date Created</th>
                </tr>
              </thead>
              <tbody>
                {% for account in accounts.items() %}
                <tr>
                  <th scope="row">
                      <input class="cb" type="checkbox" value="{{ account.id }}" />
                  </th>
                    <th>
                        <a href="{{ url_for('accounts.update_account', account_id=account.id) }}" class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="edit"></span>
                        </a>
                        <a href="#" class="btn btn-outline-secondary btn-sm mr-1"
                           data-target="#accountDeleteNotificationModal_{{ account.id }}" data-toggle="modal" role="button">
                            <span data-feather="trash"></span>
                        </a>
                        {% with acc=account %}
                            {% include 'accounts/single_account_delete_modal.html' %}
                        {% endwith %}
                        <a href="{{ url_for('accounts.get_account_view', account_id=account.id) }}"
                           class="btn btn-outline-secondary btn-sm mr-1" role="button">
                            <span data-feather="arrow-up-right"></span>
                        </a>
                    </th>
                    <td>{{ account.name }}</td>
                  <td>{{ account.email }}</td>
                  <td>
                      {% if account.website %}
                        <a href="{{ account.website }}" target="_blank">{{ account.website }}</a>
                      {% endif %}
                  </td>
                    <td>{{ account.phone }}</td>
                    <td>{{ account.address_line }}</td>
                    <td>{{ account.addr_state }}</td>
                    <td>{{ account.addr_city }}</td>
                    <td>{{ account.post_code }}</td>
                    <td>{{ account.country }}</td>
                    <td>{{ account.is_active }}</td>
                    <td>{% with owner=account.account_owner %}{% include 'common/owner_cell.html' %}{% endwith %}</td>
                    <td>{{ account.date_created.strftime('%Y-%m-%d') if account.date_created }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>

        <!-- pagination -->
        {% if accounts.total_records > 10 %}
            {% with view_id="accounts.get_accounts_view", items=accounts %}
                {% include "common/pagination.html" %}
            {% endwith %}
        {% endif %}
    {% else %}
        <div class="container text-center pt-4">
            <div><span data-feather="eye-off"></span></div>
            <p>No accounts found. Please create your first account.</p>
        </div>
    {%  endif %}
<script>
    $(document).ready(function() {
        $('#select_all').on('click', function() {
            if ($(this).is(':checked')) {
                $('.cb').prop('checked', true);
            } else {
                $('.cb').prop('checked', false);
            }
        });
    });
</script>
{% endblock %}

eeazycrm/templates/accounts/filters.html
<form class="form-lead-filter" method="POST">
    {{ filters.hidden_tag() }} <!-- security 'csrf' token -->
    <div class="d-flex flex-column justify-content-between flex-wrap flex-md-nowrap pb-4 mb-3">
        <div class="mb-2"><strong>Filters</strong></div>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="col-md-3 pl-0">
                {{ filters.txt_search(class="form-control from-control-lg", placeholder="search accounts ...") }}
            </div>
            {% if current_user.is_admin %}
            <div class="col-md-3 pl-0">
                <div class="form-group text-left">
                    {{ filters.assignees(class="my-select form-control") }}
                </div>
            </div>
            {% endif %}
            <div class="col-md-3 pl-0">
                <div class="form-group text-left">
                     {{ filters.advanced_user(class="my-select form-control") }}
                </div>
            </div>
        </div>
        <div class="btn-toolbar mb-1 mb-md-0">
            <div class="col-md-3 pl-0">
                {{ filters.submit(class="btn btn-md btn-outline-info mr-2") }}
                <a href="{{ url_for('accounts.reset_filters') }}" class="btn btn-md btn-outline-secondary" role="button">
                    <span data-feather="x-circle"></span>
                </a>
            </div>
        </div>
    </div>
</form>